### ISSUE TITLE
MetroTextbox - Resize issue

### ISSUE THREAD

**Issue by vantm** [dennismagno/metroframework-modern-ui#59]
Hi Dennis,

When I resize the form, the textbox is not rendered well.
![2017-12-03_21-02-54](https://user-images.githubusercontent.com/6279921/33526067-63f10f26-d86d-11e7-9b31-3b453061e289.gif)

Thanks,
Van T.

**Comment by simonetos** [comment]
Have you set **DoubleBuffered** -> **True** in your form's properties?

**Comment by PasanBhanu** [comment]
> Double buffering uses a memory buffer to address the flicker problems associated with multiple paint operations. When double buffering is enabled, all paint operations are first rendered to a memory buffer instead of the drawing surface on the screen. After all paint operations are completed, the memory buffer is copied directly to the drawing surface associated with it. Because only one graphics operation is performed on the screen, the image flickering associated with complex painting operations is eliminated.For most applications, the default double buffering provided by the .NET Framework will provide the best results. Standard Windows Forms controls are double buffered by default.

Try by setting Double Buffered = True in Form Properties

This happens when your computer performance (graphical) not sufficient to render redrawing of WinForms.

Source : [https://msdn.microsoft.com/en-us/library/system.windows.forms.control.doublebuffered(v=vs.110).aspx]
[(https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-reduce-graphics-flicker-with-double-buffering-for-forms-and-controls)]
